version: '2'
services:
    manatee-app:
        image: fzsun316/manatee:0.2.1
        external_links:
            - manatee-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/manatee?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 80:8080
    manatee-mysql:
        extends:
            file: mysql.yml
            service: manatee-mysql
